apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: tensorboard
  name: tensorboard
  namespace: zz-cd
  selfLink: /apis/apps.openshift.io/v1/namespaces/zz-cd/deploymentconfigs/tensorboard
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: tensorboard
    deploymentconfig: tensorboard
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: tensorboard
        deploymentconfig: tensorboard
    spec:
      containers:
        - env:
            - name: MODEL_NAME
              value: tensorboard
          image: >-
            172.30.21.196:5000/zz-cd/tensorboard@sha256:ff9b70044920abe1f683f34cad6f6f94d9684d46a12cb6c2e7a9996e3231c6d8
          imagePullPolicy: Always
          name: tensorboard
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - tensorboard
        from:
          kind: ImageStreamTag
          name: 'tensorboard:latest'
          namespace: zz-cd
        lastTriggeredImage: >-
          172.30.21.196:5000/zz-cd/tensorboard@sha256:ff9b70044920abe1f683f34cad6f6f94d9684d46a12cb6c2e7a9996e3231c6d8
      type: ImageChange
status: