apiVersion: v1
kind: Service
metadata:
  labels:
    app: tensorboard
  name: tensorboard
  namespace: zz-cd
  selfLink: /api/v1/namespaces/zz-cd/services/tensorboard
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tensorbboard
  sessionAffinity: None
  type: ClusterIP
status:
